# Generated by Django 4.1.1 on 2022-11-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portoflioapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img',
            field=models.ImageField(default=False, upload_to=''),
            preserve_default=False,
        ),
    ]
