# Generated by Django 4.1.1 on 2022-11-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portoflioapp', '0002_project_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='img',
        ),
    ]
