# Generated by Django 4.1.1 on 2022-11-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portoflioapp", "0003_remove_project_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("value", models.IntegerField(blank=True)),
                ("img", models.ImageField(blank=True, upload_to="")),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="skills",
            field=models.ManyToManyField(to="portoflioapp.skill"),
        ),
    ]
