# Generated by Django 4.1.1 on 2022-11-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portoflioapp", "0005_alter_skill_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="img",
        ),
        migrations.AddField(
            model_name="project",
            name="img",
            field=models.ImageField(default=False, upload_to="images/"),
            preserve_default=False,
        ),
    ]
